import { dom, library } from '@fortawesome/fontawesome-svg-core'

import {
  faAddressBook as falAddressBook,
  faCartShopping as falCartShopping,
  faChevronLeft as falChevronLeft,
  faChevronRight as falChevronRight,
  faChevronUp as falChevronUp,
  faCircleInfo as falCircleInfo,
  faClipboardList as falClipBoardList,
  faCloudArrowUp as falCloudArrowUp,
  faGear as falGear,
  faHouse as falHouse,
  faMegaphone as falMegaphone,
  faMessages as falMessages,
  faMobileNotch as falMobileNotch,
  faQrcode as falQrcode,
  faRectangleHistoryCirclePlus as falRectangleHistoryCirclePlus,
  faStore as falStore,
  faTable as falTable,
  faUpload as falUpload,
  faUserPlus as falUserPlus,
  faUsers as falUsers,
  faXmark as falXmark,
  faSidebar as falSidebar,
  faSidebarFlip as falSidebarFlip,
  faSlidersSimple as falSlidersSimple,
  faCode as falCode,
  faOption as falOption,
  faLink as falLink,
  faFilePdf as falFilePdf,
  faEnvelope as falEnvelope,
  faPhone as falPhone,
  faBrowser as falBrowser,
  faTrashCan as falTrashCan,
  faLinkSimple as falLinkSimple,
  faMagnifyingGlassPlus as falMagnifyingGlassPlus,
  faMagnifyingGlassMinus as falMagnifyingGlassMinus,
  faDesktop as falDesktop,
  faTablet as falTablet,
  faMobile as falMobile,
  faCloudUpload as falCloudUpload,
  faCloudArrowDown as falCloudArrowDown,
  faWavePulse as falWavePUlse,
  faBell as falBell,
  faGrid as falGrid,
} from '@fortawesome/pro-light-svg-icons'

import {
  faArrowLeft as farArrowLeft,
  faArrowRight as farArrowRight,
  faArrowRightFromBracket as farArrowRightFromBracket,
  faBoltLightning as farBoltLightning,
  faCalendar as farCalendar,
  faCircleQuestion as farCircleQuestion,
  faCode as farCode,
  faCodeCompare as farCodeCompare,
  faCopy as farCopy,
  faEnvelope as farEnvelope,
  faFolder as farFolder,
  faFolderArrowUp as farFolderArrowUp,
  faGear as farGear,
  faHamburger as farHamburger,
  faMagicWandSparkles as farMagicWandSparkles,
  faMagnifyingGlass as farMagnifyingGlass,
  faMessageLines as farMessageLines,
  faPen as farPen,
  faPencil as farPencil,
  faPlus as farPlus,
  faRocket as farRocket,
  faRotateRight as farRotateRight,
  faSparkles as farSparkles,
  faTrash as farTrash,
  faTrashCan as farTrashCan,
  faUser as farUser,
  faPage as farPage,
  faCircleInfo as farCircleInfo,
  faUserGroup as farUserGroup,
  faEye as farEye,
  faPhone as farPhone,
  faBoxesStacked as farBoxesStacked,
  faShare as farShare,
  faCloudArrowUp as farCloudArrowUp,
  faFileInvoice as farFileInvoice,
  faRectangleHistoryCircleUser as farRectangleHistoryCircleUser,
  faSpinnerScale as farSpinnerScale,
  faTimeline as farTimeline,
  faImagePolaroidUser as farImagePolaroidUser,
  faUserTag as farUserTag,
  faPartyHorn as farPartyHorn,
  faUserPen as farUserPen,
  faEllipsis as farEllipsis,
  faPlay as farPlay,
  faCircleExclamation as farCircleExclamation,
  faCirclePlus as farCirclePlus,
  faArrowTurnDownRight as farArrowTurnDownRight,
  faEllipsisVertical as farEllipsisVertical,
  faShareNodes as farShareNodes,
  faArrowRotateLeft as farArrowRotateLeft,
  faArrowRotateRight as farArrowRotateRight,
  faArrowLeftToBracket as farArrowLeftToBracket,
  faSparkles as farFarkles,
} from '@fortawesome/pro-regular-svg-icons'

import {
  faAddressBook as fasAddressBook,
  faArrowDown as fasArrowDown,
  faBars as fasBars,
  faCartShopping as fasCartShopping,
  faCheck as fasCheck,
  faChevronDown as fasChevronDown,
  faChevronRight as fasChevronRight,
  faChevronUp as fasChevronUp,
  faCircle as fasCircle,
  faClipboardList as fasClipboardList,
  faEllipsisVertical as fasEllipsisVertical,
  faDroplet as fasDroplet,
  faEye as fasEye,
  faFire as fasFire,
  faGear as fasGear,
  faHouse as fasHouse,
  faMegaphone as fasMegaphone,
  faMessages as fasMessages,
  faMobileNotch as fasMobileNotch,
  faPhone as fasPhone,
  faPlus as fasPlus,
  faRectangleHistoryCirclePlus as fasRectangleHistoryCirclePlus,
  faStore as fasStore,
  faUserPlus as fasUserPlus,
  faUsers as fasUsers,
  faXmark as fasXmark,
  faCircleNotch as fasCircleNotch,
  faGripDotsVertical as fasGripDotsVertical,
  faChevronLeft as fasChevronLeft,
} from '@fortawesome/pro-solid-svg-icons'

import {
  faFacebookF as fabFacebookF,
  faInstagram as fabInstagram,
  faLinkedin as fabLinkedin,
  faPinterest as fabPinterest,
  faTiktok as fabTiktok,
  faTwitter as fabTwitter,
  faWeixin as fabWeixin,
  faWhatsapp as fabWhatsapp,
  faYoutube as fabYoutube,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  farRotateRight,
  farArrowLeft,
  farArrowRight,
  farFolderArrowUp,
  farHamburger,
  fasHouse,
  falHouse,
  fasUserPlus,
  falUserPlus,
  farMessageLines,
  fasMessages,
  falMessages,
  fasRectangleHistoryCirclePlus,
  falRectangleHistoryCirclePlus,
  fasChevronUp,
  falChevronUp,
  fasChevronRight,
  falChevronLeft,
  falChevronRight,
  fasCartShopping,
  falCartShopping,
  fasMegaphone,
  falMegaphone,
  fasStore,
  falStore,
  fasMobileNotch,
  falMobileNotch,
  fasUsers,
  falUsers,
  fasGear,
  falGear,
  farMagnifyingGlass,
  farCircleQuestion,
  fasEye,
  fasEllipsisVertical,
  fasDroplet,
  farCode,
  farFolder,
  farMagicWandSparkles,
  fasChevronDown,
  farArrowRightFromBracket,
  farBoltLightning,
  farCopy,
  farEnvelope,
  farPen,
  farPencil,
  farPlus,
  farRocket,
  farGear,
  farSparkles,
  farTrash,
  farTrashCan,
  farUser,
  fabFacebookF,
  fabTwitter,
  fabInstagram,
  fabYoutube,
  fabPinterest,
  fabLinkedin,
  fabTiktok,
  fabWeixin,
  fabWhatsapp,
  fasBars,
  fasPhone,
  fasFire,
  fasCircle,
  falQrcode,
  fasCheck,
  falCircleInfo,
  farCalendar,
  farCodeCompare,
  falXmark,
  fasXmark,
  falCloudArrowUp,
  fasClipboardList,
  falClipBoardList,
  fasAddressBook,
  falAddressBook,
  fasPlus,
  fasArrowDown,
  farPage,
  farCircleInfo,
  fasCircleNotch,
  falTable,
  falUpload,
  farUserGroup,
  farEye,
  farPhone,
  farBoxesStacked,
  farShare,
  farCloudArrowUp,
  farFileInvoice,
  farRectangleHistoryCircleUser,
  farTimeline,
  farImagePolaroidUser,
  farSpinnerScale,
  farUserTag,
  farPartyHorn,
  farUserPen,
  farEllipsis,
  falDesktop,
  falTablet,
  falMobile,
  falMagnifyingGlassPlus,
  falMagnifyingGlassMinus,
  falSidebar,
  falSidebarFlip,
  falSlidersSimple,
  falCode,
  falOption,
  falLink,
  falFilePdf,
  falEnvelope,
  falPhone,
  falBrowser,
  falTrashCan,
  farPlay,
  falLinkSimple,
  farCircleExclamation,
  falCloudUpload,
  fasGripDotsVertical,
  farCirclePlus,
  farArrowTurnDownRight,
  falCloudArrowDown,
  farEllipsisVertical,
  farShareNodes,
  farArrowRotateLeft,
  farArrowRotateRight,
  farArrowLeftToBracket,
  falWavePUlse,
  falBell,
  falGrid,
  farFarkles,
  fasChevronLeft,
)

dom.watch()
