cacheFolder: .yarn/cache

enableImmutableInstalls: true

nodeLinker: node-modules

injectEnvironmentFiles:
  - .env.local?

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
