ARG RUBY_VERSION=3.4.2
FROM ruby:$RUBY_VERSION
ARG YARN_VERSION=4.7.0

# Install dependencies
RUN apt-get update -qq
RUN apt-get install --no-install-recommends -y build-essential curl nodejs npm libpq-dev && \
    npm install -g corepack && \
    corepack enable && \
    corepack prepare yarn@$YARN_VERSION --activate

WORKDIR /rails

# Copy application
COPY . .

# Install Ruby dependencies
RUN gem install bundler:2.6.5
RUN bundle install

# Clean and install JavaScript dependencies
RUN rm -rf node_modules package-lock.json && \
    npm cache clean --force && \
    yarn install

# Build the typescript and javascript files
RUN yarn build
