default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fluid_droplets_development

test:
  <<: *default
  database: fluid_droplets_test

production:
  primary: &primary_production
    <<: *default
    database: fluid_droplets_production
    username: fluid_droplets
    password: <%= ENV["FLUID_DROPLETS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: fluid_droplets_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fluid_droplets_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fluid_droplets_production_cable
    migrations_paths: db/cable_migrate
