default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: droplet_template_development

test:
  <<: *default
  database: droplet_template_test

production:
  primary: &primary_production
    <<: *default
    database: droplet_template_production
    username: droplet_template
    password: <%= ENV["DROPLET_TEMPLATE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: droplet_template_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: droplet_template_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: droplet_template_production_cable
    migrations_paths: db/cable_migrate
